/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : AlertId,
  'alertType' : AlertType,
  'acknowledged' : boolean,
  'message' : string,
  'deviceId' : DeviceId,
  'timestamp' : Time,
  'severity' : Severity,
}
export type AlertId = string;
export type AlertType = { 'temperature' : null } |
  { 'flow' : null } |
  { 'heat' : null } |
  { 'vibration' : null } |
  { 'level' : null };
export interface DashboardStats {
  'cloudStatus' : string,
  'activeDevices' : bigint,
  'unreadAlerts' : bigint,
  'totalDataPoints' : bigint,
}
export interface Device {
  'id' : DeviceId,
  'name' : string,
  'isOnline' : boolean,
  'description' : string,
  'lastSeen' : Time,
  'location' : string,
}
export type DeviceId = string;
export interface SensorData {
  'temperature' : number,
  'flow' : number,
  'heat' : number,
  'vibration' : number,
  'level' : number,
  'timestamp' : Time,
}
export type Severity = { 'warning' : null } |
  { 'info' : null } |
  { 'critical' : null };
export type Time = bigint;
export interface _SERVICE {
  'acknowledgeAlert' : ActorMethod<[AlertId], undefined>,
  'createAlert' : ActorMethod<
    [DeviceId, AlertType, string, Severity],
    undefined
  >,
  'getAllLatestReadings' : ActorMethod<
    [],
    Array<[DeviceId, [] | [SensorData]]>
  >,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getHistoricalReadings' : ActorMethod<[DeviceId, bigint], Array<SensorData>>,
  'getLatestReading' : ActorMethod<[DeviceId], [] | [SensorData]>,
  'getRecentAlerts' : ActorMethod<[bigint], Array<Alert>>,
  'ingestSensorData' : ActorMethod<
    [DeviceId, number, number, number, number, number],
    undefined
  >,
  'listDevices' : ActorMethod<[], Array<[DeviceId, Device]>>,
  'registerDevice' : ActorMethod<[DeviceId, string, string, string], undefined>,
  'updateDeviceStatus' : ActorMethod<[DeviceId, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];