/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AlertId = IDL.Text;
export const DeviceId = IDL.Text;
export const AlertType = IDL.Variant({
  'temperature' : IDL.Null,
  'flow' : IDL.Null,
  'heat' : IDL.Null,
  'vibration' : IDL.Null,
  'level' : IDL.Null,
});
export const Severity = IDL.Variant({
  'warning' : IDL.Null,
  'info' : IDL.Null,
  'critical' : IDL.Null,
});
export const Time = IDL.Int;
export const SensorData = IDL.Record({
  'temperature' : IDL.Float64,
  'flow' : IDL.Float64,
  'heat' : IDL.Float64,
  'vibration' : IDL.Float64,
  'level' : IDL.Float64,
  'timestamp' : Time,
});
export const DashboardStats = IDL.Record({
  'cloudStatus' : IDL.Text,
  'activeDevices' : IDL.Nat,
  'unreadAlerts' : IDL.Nat,
  'totalDataPoints' : IDL.Nat,
});
export const Alert = IDL.Record({
  'id' : AlertId,
  'alertType' : AlertType,
  'acknowledged' : IDL.Bool,
  'message' : IDL.Text,
  'deviceId' : DeviceId,
  'timestamp' : Time,
  'severity' : Severity,
});
export const Device = IDL.Record({
  'id' : DeviceId,
  'name' : IDL.Text,
  'isOnline' : IDL.Bool,
  'description' : IDL.Text,
  'lastSeen' : Time,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'acknowledgeAlert' : IDL.Func([AlertId], [], []),
  'createAlert' : IDL.Func([DeviceId, AlertType, IDL.Text, Severity], [], []),
  'getAllLatestReadings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(DeviceId, IDL.Opt(SensorData)))],
      ['query'],
    ),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getHistoricalReadings' : IDL.Func(
      [DeviceId, IDL.Nat],
      [IDL.Vec(SensorData)],
      ['query'],
    ),
  'getLatestReading' : IDL.Func([DeviceId], [IDL.Opt(SensorData)], ['query']),
  'getRecentAlerts' : IDL.Func([IDL.Nat], [IDL.Vec(Alert)], ['query']),
  'ingestSensorData' : IDL.Func(
      [
        DeviceId,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'listDevices' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(DeviceId, Device))],
      ['query'],
    ),
  'registerDevice' : IDL.Func([DeviceId, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateDeviceStatus' : IDL.Func([DeviceId, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AlertId = IDL.Text;
  const DeviceId = IDL.Text;
  const AlertType = IDL.Variant({
    'temperature' : IDL.Null,
    'flow' : IDL.Null,
    'heat' : IDL.Null,
    'vibration' : IDL.Null,
    'level' : IDL.Null,
  });
  const Severity = IDL.Variant({
    'warning' : IDL.Null,
    'info' : IDL.Null,
    'critical' : IDL.Null,
  });
  const Time = IDL.Int;
  const SensorData = IDL.Record({
    'temperature' : IDL.Float64,
    'flow' : IDL.Float64,
    'heat' : IDL.Float64,
    'vibration' : IDL.Float64,
    'level' : IDL.Float64,
    'timestamp' : Time,
  });
  const DashboardStats = IDL.Record({
    'cloudStatus' : IDL.Text,
    'activeDevices' : IDL.Nat,
    'unreadAlerts' : IDL.Nat,
    'totalDataPoints' : IDL.Nat,
  });
  const Alert = IDL.Record({
    'id' : AlertId,
    'alertType' : AlertType,
    'acknowledged' : IDL.Bool,
    'message' : IDL.Text,
    'deviceId' : DeviceId,
    'timestamp' : Time,
    'severity' : Severity,
  });
  const Device = IDL.Record({
    'id' : DeviceId,
    'name' : IDL.Text,
    'isOnline' : IDL.Bool,
    'description' : IDL.Text,
    'lastSeen' : Time,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'acknowledgeAlert' : IDL.Func([AlertId], [], []),
    'createAlert' : IDL.Func([DeviceId, AlertType, IDL.Text, Severity], [], []),
    'getAllLatestReadings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(DeviceId, IDL.Opt(SensorData)))],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getHistoricalReadings' : IDL.Func(
        [DeviceId, IDL.Nat],
        [IDL.Vec(SensorData)],
        ['query'],
      ),
    'getLatestReading' : IDL.Func([DeviceId], [IDL.Opt(SensorData)], ['query']),
    'getRecentAlerts' : IDL.Func([IDL.Nat], [IDL.Vec(Alert)], ['query']),
    'ingestSensorData' : IDL.Func(
        [
          DeviceId,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'listDevices' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(DeviceId, Device))],
        ['query'],
      ),
    'registerDevice' : IDL.Func(
        [DeviceId, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateDeviceStatus' : IDL.Func([DeviceId, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };