/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type DeviceId = string;
export type Time = bigint;
export interface SensorData {
    temperature: number;
    flow: number;
    heat: number;
    vibration: number;
    level: number;
    timestamp: Time;
}
export type AlertId = string;
export interface DashboardStats {
    cloudStatus: string;
    activeDevices: bigint;
    unreadAlerts: bigint;
    totalDataPoints: bigint;
}
export interface Device {
    id: DeviceId;
    name: string;
    isOnline: boolean;
    description: string;
    lastSeen: Time;
    location: string;
}
export interface Alert {
    id: AlertId;
    alertType: AlertType;
    acknowledged: boolean;
    message: string;
    deviceId: DeviceId;
    timestamp: Time;
    severity: Severity;
}
export enum AlertType {
    temperature = "temperature",
    flow = "flow",
    heat = "heat",
    vibration = "vibration",
    level = "level"
}
export enum Severity {
    warning = "warning",
    info = "info",
    critical = "critical"
}
export interface backendInterface {
    acknowledgeAlert(alertId: AlertId): Promise<void>;
    createAlert(deviceId: DeviceId, alertType: AlertType, message: string, severity: Severity): Promise<void>;
    getAllLatestReadings(): Promise<Array<[DeviceId, SensorData | null]>>;
    getDashboardStats(): Promise<DashboardStats>;
    getHistoricalReadings(deviceId: DeviceId, count: bigint): Promise<Array<SensorData>>;
    getLatestReading(deviceId: DeviceId): Promise<SensorData | null>;
    getRecentAlerts(count: bigint): Promise<Array<Alert>>;
    ingestSensorData(deviceId: DeviceId, temperature: number, heat: number, level: number, flow: number, vibration: number): Promise<void>;
    listDevices(): Promise<Array<[DeviceId, Device]>>;
    registerDevice(id: DeviceId, name: string, location: string, description: string): Promise<void>;
    updateDeviceStatus(id: DeviceId, isOnline: boolean): Promise<void>;
}
import type { Alert as _Alert, AlertId as _AlertId, AlertType as _AlertType, DeviceId as _DeviceId, SensorData as _SensorData, Severity as _Severity, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acknowledgeAlert(arg0: AlertId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acknowledgeAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acknowledgeAlert(arg0);
            return result;
        }
    }
    async createAlert(arg0: DeviceId, arg1: AlertType, arg2: string, arg3: Severity): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAlert(arg0, to_candid_AlertType_n1(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_Severity_n3(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAlert(arg0, to_candid_AlertType_n1(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_Severity_n3(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async getAllLatestReadings(): Promise<Array<[DeviceId, SensorData | null]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLatestReadings();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLatestReadings();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getHistoricalReadings(arg0: DeviceId, arg1: bigint): Promise<Array<SensorData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistoricalReadings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistoricalReadings(arg0, arg1);
            return result;
        }
    }
    async getLatestReading(arg0: DeviceId): Promise<SensorData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestReading(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestReading(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentAlerts(arg0: bigint): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentAlerts(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentAlerts(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async ingestSensorData(arg0: DeviceId, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.ingestSensorData(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ingestSensorData(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async listDevices(): Promise<Array<[DeviceId, Device]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDevices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDevices();
            return result;
        }
    }
    async registerDevice(arg0: DeviceId, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerDevice(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerDevice(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateDeviceStatus(arg0: DeviceId, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeviceStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeviceStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AlertType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertType): AlertType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Alert_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Alert): Alert {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Severity_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Severity): Severity {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SensorData]): SensorData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AlertId;
    alertType: _AlertType;
    acknowledged: boolean;
    message: string;
    deviceId: _DeviceId;
    timestamp: _Time;
    severity: _Severity;
}): {
    id: AlertId;
    alertType: AlertType;
    acknowledged: boolean;
    message: string;
    deviceId: DeviceId;
    timestamp: Time;
    severity: Severity;
} {
    return {
        id: value.id,
        alertType: from_candid_AlertType_n11(_uploadFile, _downloadFile, value.alertType),
        acknowledged: value.acknowledged,
        message: value.message,
        deviceId: value.deviceId,
        timestamp: value.timestamp,
        severity: from_candid_Severity_n13(_uploadFile, _downloadFile, value.severity)
    };
}
function from_candid_tuple_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_DeviceId, [] | [_SensorData]]): [DeviceId, SensorData | null] {
    return [
        value[0],
        from_candid_opt_n7(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    temperature: null;
} | {
    flow: null;
} | {
    heat: null;
} | {
    vibration: null;
} | {
    level: null;
}): AlertType {
    return "temperature" in value ? AlertType.temperature : "flow" in value ? AlertType.flow : "heat" in value ? AlertType.heat : "vibration" in value ? AlertType.vibration : "level" in value ? AlertType.level : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    warning: null;
} | {
    info: null;
} | {
    critical: null;
}): Severity {
    return "warning" in value ? Severity.warning : "info" in value ? Severity.info : "critical" in value ? Severity.critical : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_DeviceId, [] | [_SensorData]]>): Array<[DeviceId, SensorData | null]> {
    return value.map((x)=>from_candid_tuple_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Alert>): Array<Alert> {
    return value.map((x)=>from_candid_Alert_n9(_uploadFile, _downloadFile, x));
}
function to_candid_AlertType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertType): _AlertType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Severity_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Severity): _Severity {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertType): {
    temperature: null;
} | {
    flow: null;
} | {
    heat: null;
} | {
    vibration: null;
} | {
    level: null;
} {
    return value == AlertType.temperature ? {
        temperature: null
    } : value == AlertType.flow ? {
        flow: null
    } : value == AlertType.heat ? {
        heat: null
    } : value == AlertType.vibration ? {
        vibration: null
    } : value == AlertType.level ? {
        level: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Severity): {
    warning: null;
} | {
    info: null;
} | {
    critical: null;
} {
    return value == Severity.warning ? {
        warning: null
    } : value == Severity.info ? {
        info: null
    } : value == Severity.critical ? {
        critical: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
